name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '38 22 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Closing this issue soon due to no activities'
        stale-pr-message: 'Closing this PR due to no activities'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
